%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Benchmark';
M_.dynare_version = '5.1';
oo_.dynare_version = '5.1';
options_.dynare_version = '5.1';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(5,1);
M_.exo_names_tex = cell(5,1);
M_.exo_names_long = cell(5,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'eps\_a'};
M_.exo_names_long(1) = {'eps_a'};
M_.exo_names(2) = {'eps_g'};
M_.exo_names_tex(2) = {'eps\_g'};
M_.exo_names_long(2) = {'eps_g'};
M_.exo_names(3) = {'eps_y_star'};
M_.exo_names_tex(3) = {'eps\_y\_star'};
M_.exo_names_long(3) = {'eps_y_star'};
M_.exo_names(4) = {'eps_r_star'};
M_.exo_names_tex(4) = {'eps\_r\_star'};
M_.exo_names_long(4) = {'eps_r_star'};
M_.exo_names(5) = {'eps_m'};
M_.exo_names_tex(5) = {'eps\_m'};
M_.exo_names_long(5) = {'eps_m'};
M_.endo_names = cell(47,1);
M_.endo_names_tex = cell(47,1);
M_.endo_names_long = cell(47,1);
M_.endo_names(1) = {'a_a'};
M_.endo_names_tex(1) = {'a\_a'};
M_.endo_names_long(1) = {'a_a'};
M_.endo_names(2) = {'a_g'};
M_.endo_names_tex(2) = {'a\_g'};
M_.endo_names_long(2) = {'a_g'};
M_.endo_names(3) = {'a_y_star'};
M_.endo_names_tex(3) = {'a\_y\_star'};
M_.endo_names_long(3) = {'a_y_star'};
M_.endo_names(4) = {'a_r_star'};
M_.endo_names_tex(4) = {'a\_r\_star'};
M_.endo_names_long(4) = {'a_r_star'};
M_.endo_names(5) = {'c'};
M_.endo_names_tex(5) = {'c'};
M_.endo_names_long(5) = {'c'};
M_.endo_names(6) = {'h'};
M_.endo_names_tex(6) = {'h'};
M_.endo_names_long(6) = {'h'};
M_.endo_names(7) = {'k'};
M_.endo_names_tex(7) = {'k'};
M_.endo_names_long(7) = {'k'};
M_.endo_names(8) = {'i'};
M_.endo_names_tex(8) = {'i'};
M_.endo_names_long(8) = {'i'};
M_.endo_names(9) = {'y_h'};
M_.endo_names_tex(9) = {'y\_h'};
M_.endo_names_long(9) = {'y_h'};
M_.endo_names(10) = {'v'};
M_.endo_names_tex(10) = {'v'};
M_.endo_names_long(10) = {'v'};
M_.endo_names(11) = {'lm1'};
M_.endo_names_tex(11) = {'lm1'};
M_.endo_names_long(11) = {'lm1'};
M_.endo_names(12) = {'c1'};
M_.endo_names_tex(12) = {'c1'};
M_.endo_names_long(12) = {'c1'};
M_.endo_names(13) = {'h1'};
M_.endo_names_tex(13) = {'h1'};
M_.endo_names_long(13) = {'h1'};
M_.endo_names(14) = {'d1'};
M_.endo_names_tex(14) = {'d1'};
M_.endo_names_long(14) = {'d1'};
M_.endo_names(15) = {'b1'};
M_.endo_names_tex(15) = {'b1'};
M_.endo_names_long(15) = {'b1'};
M_.endo_names(16) = {'b_f1'};
M_.endo_names_tex(16) = {'b\_f1'};
M_.endo_names_long(16) = {'b_f1'};
M_.endo_names(17) = {'v1'};
M_.endo_names_tex(17) = {'v1'};
M_.endo_names_long(17) = {'v1'};
M_.endo_names(18) = {'lm2'};
M_.endo_names_tex(18) = {'lm2'};
M_.endo_names_long(18) = {'lm2'};
M_.endo_names(19) = {'c2'};
M_.endo_names_tex(19) = {'c2'};
M_.endo_names_long(19) = {'c2'};
M_.endo_names(20) = {'h2'};
M_.endo_names_tex(20) = {'h2'};
M_.endo_names_long(20) = {'h2'};
M_.endo_names(21) = {'v2'};
M_.endo_names_tex(21) = {'v2'};
M_.endo_names_long(21) = {'v2'};
M_.endo_names(22) = {'r_d'};
M_.endo_names_tex(22) = {'r\_d'};
M_.endo_names_long(22) = {'r_d'};
M_.endo_names(23) = {'r_k'};
M_.endo_names_tex(23) = {'r\_k'};
M_.endo_names_long(23) = {'r_k'};
M_.endo_names(24) = {'w'};
M_.endo_names_tex(24) = {'w'};
M_.endo_names_long(24) = {'w'};
M_.endo_names(25) = {'q'};
M_.endo_names_tex(25) = {'q'};
M_.endo_names_long(25) = {'q'};
M_.endo_names(26) = {'mc'};
M_.endo_names_tex(26) = {'mc'};
M_.endo_names_long(26) = {'mc'};
M_.endo_names(27) = {'pi_h'};
M_.endo_names_tex(27) = {'pi\_h'};
M_.endo_names_long(27) = {'pi_h'};
M_.endo_names(28) = {'pi'};
M_.endo_names_tex(28) = {'pi'};
M_.endo_names_long(28) = {'pi'};
M_.endo_names(29) = {'p_h'};
M_.endo_names_tex(29) = {'p\_h'};
M_.endo_names_long(29) = {'p_h'};
M_.endo_names(30) = {'s'};
M_.endo_names_tex(30) = {'s'};
M_.endo_names_long(30) = {'s'};
M_.endo_names(31) = {'delta_e'};
M_.endo_names_tex(31) = {'delta\_e'};
M_.endo_names_long(31) = {'delta_e'};
M_.endo_names(32) = {'r'};
M_.endo_names_tex(32) = {'r'};
M_.endo_names_long(32) = {'r'};
M_.endo_names(33) = {'t1'};
M_.endo_names_tex(33) = {'t1'};
M_.endo_names_long(33) = {'t1'};
M_.endo_names(34) = {'t2'};
M_.endo_names_tex(34) = {'t2'};
M_.endo_names_long(34) = {'t2'};
M_.endo_names(35) = {'log_y'};
M_.endo_names_tex(35) = {'log\_y'};
M_.endo_names_long(35) = {'log_y'};
M_.endo_names(36) = {'log_c'};
M_.endo_names_tex(36) = {'log\_c'};
M_.endo_names_long(36) = {'log_c'};
M_.endo_names(37) = {'log_c1'};
M_.endo_names_tex(37) = {'log\_c1'};
M_.endo_names_long(37) = {'log_c1'};
M_.endo_names(38) = {'log_c2'};
M_.endo_names_tex(38) = {'log\_c2'};
M_.endo_names_long(38) = {'log_c2'};
M_.endo_names(39) = {'log_r'};
M_.endo_names_tex(39) = {'log\_r'};
M_.endo_names_long(39) = {'log_r'};
M_.endo_names(40) = {'log_r_d'};
M_.endo_names_tex(40) = {'log\_r\_d'};
M_.endo_names_long(40) = {'log_r_d'};
M_.endo_names(41) = {'log_pi_h'};
M_.endo_names_tex(41) = {'log\_pi\_h'};
M_.endo_names_long(41) = {'log_pi_h'};
M_.endo_names(42) = {'log_p_h'};
M_.endo_names_tex(42) = {'log\_p\_h'};
M_.endo_names_long(42) = {'log_p_h'};
M_.endo_names(43) = {'log_s'};
M_.endo_names_tex(43) = {'log\_s'};
M_.endo_names_long(43) = {'log_s'};
M_.endo_names(44) = {'log_tot'};
M_.endo_names_tex(44) = {'log\_tot'};
M_.endo_names_long(44) = {'log_tot'};
M_.endo_names(45) = {'log_pi'};
M_.endo_names_tex(45) = {'log\_pi'};
M_.endo_names_long(45) = {'log_pi'};
M_.endo_names(46) = {'log_w'};
M_.endo_names_tex(46) = {'log\_w'};
M_.endo_names_long(46) = {'log_w'};
M_.endo_names(47) = {'log_d1'};
M_.endo_names_tex(47) = {'log\_d1'};
M_.endo_names_long(47) = {'log_d1'};
M_.endo_partitions = struct();
M_.param_names = cell(50,1);
M_.param_names_tex = cell(50,1);
M_.param_names_long = cell(50,1);
M_.param_names(1) = {'LAMBDA'};
M_.param_names_tex(1) = {'LAMBDA'};
M_.param_names_long(1) = {'LAMBDA'};
M_.param_names(2) = {'BETA'};
M_.param_names_tex(2) = {'BETA'};
M_.param_names_long(2) = {'BETA'};
M_.param_names(3) = {'SIGMA'};
M_.param_names_tex(3) = {'SIGMA'};
M_.param_names_long(3) = {'SIGMA'};
M_.param_names(4) = {'CHI'};
M_.param_names_tex(4) = {'CHI'};
M_.param_names_long(4) = {'CHI'};
M_.param_names(5) = {'PHI'};
M_.param_names_tex(5) = {'PHI'};
M_.param_names_long(5) = {'PHI'};
M_.param_names(6) = {'ETA'};
M_.param_names_tex(6) = {'ETA'};
M_.param_names_long(6) = {'ETA'};
M_.param_names(7) = {'GAMMA'};
M_.param_names_tex(7) = {'GAMMA'};
M_.param_names_long(7) = {'GAMMA'};
M_.param_names(8) = {'GAMMA_STAR'};
M_.param_names_tex(8) = {'GAMMA\_STAR'};
M_.param_names_long(8) = {'GAMMA_STAR'};
M_.param_names(9) = {'A'};
M_.param_names_tex(9) = {'A'};
M_.param_names_long(9) = {'A'};
M_.param_names(10) = {'B'};
M_.param_names_tex(10) = {'B'};
M_.param_names_long(10) = {'B'};
M_.param_names(11) = {'ALPHA'};
M_.param_names_tex(11) = {'ALPHA'};
M_.param_names_long(11) = {'ALPHA'};
M_.param_names(12) = {'DELTA'};
M_.param_names_tex(12) = {'DELTA'};
M_.param_names_long(12) = {'DELTA'};
M_.param_names(13) = {'KAPPA_P'};
M_.param_names_tex(13) = {'KAPPA\_P'};
M_.param_names_long(13) = {'KAPPA_P'};
M_.param_names(14) = {'EPSILON'};
M_.param_names_tex(14) = {'EPSILON'};
M_.param_names_long(14) = {'EPSILON'};
M_.param_names(15) = {'KAPPA_I'};
M_.param_names_tex(15) = {'KAPPA\_I'};
M_.param_names_long(15) = {'KAPPA_I'};
M_.param_names(16) = {'EPSILON_B'};
M_.param_names_tex(16) = {'EPSILON\_B'};
M_.param_names_long(16) = {'EPSILON_B'};
M_.param_names(17) = {'KAPPA_B'};
M_.param_names_tex(17) = {'KAPPA\_B'};
M_.param_names_long(17) = {'KAPPA_B'};
M_.param_names(18) = {'BF_BAR'};
M_.param_names_tex(18) = {'BF\_BAR'};
M_.param_names_long(18) = {'BF_BAR'};
M_.param_names(19) = {'PHI_B'};
M_.param_names_tex(19) = {'PHI\_B'};
M_.param_names_long(19) = {'PHI_B'};
M_.param_names(20) = {'PHI_M'};
M_.param_names_tex(20) = {'PHI\_M'};
M_.param_names_long(20) = {'PHI_M'};
M_.param_names(21) = {'PHI_G'};
M_.param_names_tex(21) = {'PHI\_G'};
M_.param_names_long(21) = {'PHI_G'};
M_.param_names(22) = {'B_BAR'};
M_.param_names_tex(22) = {'B\_BAR'};
M_.param_names_long(22) = {'B_BAR'};
M_.param_names(23) = {'M_BAR'};
M_.param_names_tex(23) = {'M\_BAR'};
M_.param_names_long(23) = {'M_BAR'};
M_.param_names(24) = {'T1_BAR'};
M_.param_names_tex(24) = {'T1\_BAR'};
M_.param_names_long(24) = {'T1_BAR'};
M_.param_names(25) = {'T2_BAR'};
M_.param_names_tex(25) = {'T2\_BAR'};
M_.param_names_long(25) = {'T2_BAR'};
M_.param_names(26) = {'RHO_R'};
M_.param_names_tex(26) = {'RHO\_R'};
M_.param_names_long(26) = {'RHO_R'};
M_.param_names(27) = {'PHI_PI'};
M_.param_names_tex(27) = {'PHI\_PI'};
M_.param_names_long(27) = {'PHI_PI'};
M_.param_names(28) = {'PHI_Y'};
M_.param_names_tex(28) = {'PHI\_Y'};
M_.param_names_long(28) = {'PHI_Y'};
M_.param_names(29) = {'PHI_E'};
M_.param_names_tex(29) = {'PHI\_E'};
M_.param_names_long(29) = {'PHI_E'};
M_.param_names(30) = {'R_BAR'};
M_.param_names_tex(30) = {'R\_BAR'};
M_.param_names_long(30) = {'R_BAR'};
M_.param_names(31) = {'PI_BAR'};
M_.param_names_tex(31) = {'PI\_BAR'};
M_.param_names_long(31) = {'PI_BAR'};
M_.param_names(32) = {'Y_BAR'};
M_.param_names_tex(32) = {'Y\_BAR'};
M_.param_names_long(32) = {'Y_BAR'};
M_.param_names(33) = {'E_BAR'};
M_.param_names_tex(33) = {'E\_BAR'};
M_.param_names_long(33) = {'E_BAR'};
M_.param_names(34) = {'DELTA_M'};
M_.param_names_tex(34) = {'DELTA\_M'};
M_.param_names_long(34) = {'DELTA_M'};
M_.param_names(35) = {'RHO_A'};
M_.param_names_tex(35) = {'RHO\_A'};
M_.param_names_long(35) = {'RHO_A'};
M_.param_names(36) = {'RHO_Z'};
M_.param_names_tex(36) = {'RHO\_Z'};
M_.param_names_long(36) = {'RHO_Z'};
M_.param_names(37) = {'RHO_G'};
M_.param_names_tex(37) = {'RHO\_G'};
M_.param_names_long(37) = {'RHO_G'};
M_.param_names(38) = {'RHO_Y_STAR'};
M_.param_names_tex(38) = {'RHO\_Y\_STAR'};
M_.param_names_long(38) = {'RHO_Y_STAR'};
M_.param_names(39) = {'RHO_R_STAR'};
M_.param_names_tex(39) = {'RHO\_R\_STAR'};
M_.param_names_long(39) = {'RHO_R_STAR'};
M_.param_names(40) = {'A_BAR'};
M_.param_names_tex(40) = {'A\_BAR'};
M_.param_names_long(40) = {'A_BAR'};
M_.param_names(41) = {'Z_BAR'};
M_.param_names_tex(41) = {'Z\_BAR'};
M_.param_names_long(41) = {'Z_BAR'};
M_.param_names(42) = {'G_BAR'};
M_.param_names_tex(42) = {'G\_BAR'};
M_.param_names_long(42) = {'G_BAR'};
M_.param_names(43) = {'Y_STAR_BAR'};
M_.param_names_tex(43) = {'Y\_STAR\_BAR'};
M_.param_names_long(43) = {'Y_STAR_BAR'};
M_.param_names(44) = {'R_STAR_BAR'};
M_.param_names_tex(44) = {'R\_STAR\_BAR'};
M_.param_names_long(44) = {'R_STAR_BAR'};
M_.param_names(45) = {'STDERR_A'};
M_.param_names_tex(45) = {'STDERR\_A'};
M_.param_names_long(45) = {'STDERR_A'};
M_.param_names(46) = {'STDERR_Z'};
M_.param_names_tex(46) = {'STDERR\_Z'};
M_.param_names_long(46) = {'STDERR_Z'};
M_.param_names(47) = {'STDERR_G'};
M_.param_names_tex(47) = {'STDERR\_G'};
M_.param_names_long(47) = {'STDERR_G'};
M_.param_names(48) = {'STDERR_Y_STAR'};
M_.param_names_tex(48) = {'STDERR\_Y\_STAR'};
M_.param_names_long(48) = {'STDERR_Y_STAR'};
M_.param_names(49) = {'STDERR_R_STAR'};
M_.param_names_tex(49) = {'STDERR\_R\_STAR'};
M_.param_names_long(49) = {'STDERR_R_STAR'};
M_.param_names(50) = {'STDERR_M'};
M_.param_names_tex(50) = {'STDERR\_M'};
M_.param_names_long(50) = {'STDERR_M'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 47;
M_.param_nbr = 50;
M_.orig_endo_nbr = 47;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [1 5 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 47;
M_.eq_nbr = 47;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 11 0;
 0 12 0;
 2 13 0;
 3 14 0;
 0 15 0;
 0 16 0;
 4 17 0;
 5 18 58;
 0 19 59;
 0 20 0;
 0 21 60;
 0 22 0;
 0 23 0;
 0 24 0;
 6 25 0;
 7 26 0;
 0 27 61;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 62;
 0 32 0;
 0 33 63;
 0 34 0;
 0 35 64;
 0 36 0;
 0 37 65;
 0 38 66;
 8 39 67;
 9 40 68;
 0 41 0;
 10 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;]';
M_.nstatic = 29;
M_.nfwrd   = 8;
M_.npred   = 7;
M_.nboth   = 3;
M_.nsfwrd   = 11;
M_.nspred   = 10;
M_.ndynamic   = 18;
M_.dynamic_tmp_nbr = [26; 41; 5; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , '1' ;
  2 , 'name' , 'c' ;
  3 , 'name' , 'h' ;
  4 , 'name' , 'k' ;
  5 , 'name' , 'y_h' ;
  6 , 'name' , 'v' ;
  7 , 'name' , '7' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'lm1' ;
  10 , 'name' , '10' ;
  11 , 'name' , '11' ;
  12 , 'name' , 'v1' ;
  13 , 'name' , '13' ;
  14 , 'name' , '14' ;
  15 , 'name' , 'c2' ;
  16 , 'name' , 'v2' ;
  17 , 'name' , 'r_d' ;
  18 , 'name' , '18' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , 'r_k' ;
  22 , 'name' , 'w' ;
  23 , 'name' , '23' ;
  24 , 'name' , 'pi_h' ;
  25 , 'name' , '25' ;
  26 , 'name' , '26' ;
  27 , 'name' , 'delta_e' ;
  28 , 'name' , '28' ;
  29 , 'name' , '29' ;
  30 , 'name' , '30' ;
  31 , 'name' , 'b1' ;
  32 , 'name' , 'a_g' ;
  33 , 'name' , 't1' ;
  34 , 'name' , 't2' ;
  35 , 'name' , 'log_y' ;
  36 , 'name' , 'log_c' ;
  37 , 'name' , 'log_c1' ;
  38 , 'name' , 'log_c2' ;
  39 , 'name' , 'log_r' ;
  40 , 'name' , 'log_r_d' ;
  41 , 'name' , 'log_pi_h' ;
  42 , 'name' , 'log_p_h' ;
  43 , 'name' , 'log_s' ;
  44 , 'name' , 'log_tot' ;
  45 , 'name' , 'log_pi' ;
  46 , 'name' , 'log_w' ;
  47 , 'name' , 'log_d1' ;
};
M_.mapping.a_a.eqidx = [1 20 ];
M_.mapping.a_g.eqidx = [5 25 32 33 34 ];
M_.mapping.a_y_star.eqidx = [5 28 ];
M_.mapping.a_r_star.eqidx = [11 25 29 ];
M_.mapping.eps_a.eqidx = [1 ];
M_.mapping.eps_g.eqidx = [32 ];
M_.mapping.eps_y_star.eqidx = [28 ];
M_.mapping.eps_r_star.eqidx = [29 ];
M_.mapping.eps_m.eqidx = [30 ];
M_.mapping.c.eqidx = [2 5 25 36 ];
M_.mapping.h.eqidx = [3 20 22 ];
M_.mapping.k.eqidx = [4 19 20 21 ];
M_.mapping.i.eqidx = [5 18 19 25 ];
M_.mapping.y_h.eqidx = [5 20 21 22 23 25 30 35 ];
M_.mapping.v.eqidx = [6 ];
M_.mapping.lm1.eqidx = [7 8 9 10 11 17 18 23 ];
M_.mapping.c1.eqidx = [2 7 12 37 ];
M_.mapping.h1.eqidx = [3 8 12 ];
M_.mapping.d1.eqidx = [4 47 ];
M_.mapping.b1.eqidx = [31 33 34 ];
M_.mapping.b_f1.eqidx = [11 25 ];
M_.mapping.v1.eqidx = [6 12 ];
M_.mapping.lm2.eqidx = [13 14 ];
M_.mapping.c2.eqidx = [2 13 15 16 38 ];
M_.mapping.h2.eqidx = [3 14 15 16 ];
M_.mapping.v2.eqidx = [6 16 ];
M_.mapping.r_d.eqidx = [9 17 40 ];
M_.mapping.r_k.eqidx = [17 21 ];
M_.mapping.w.eqidx = [8 14 15 22 46 ];
M_.mapping.q.eqidx = [17 18 ];
M_.mapping.mc.eqidx = [21 22 23 ];
M_.mapping.pi_h.eqidx = [5 23 24 25 41 ];
M_.mapping.pi.eqidx = [9 10 17 24 27 30 33 34 45 ];
M_.mapping.p_h.eqidx = [5 23 24 25 26 30 35 42 44 ];
M_.mapping.s.eqidx = [5 11 25 26 27 43 44 ];
M_.mapping.delta_e.eqidx = [27 30 ];
M_.mapping.r.eqidx = [10 30 33 34 39 ];
M_.mapping.t1.eqidx = [33 ];
M_.mapping.t2.eqidx = [15 34 ];
M_.mapping.log_y.eqidx = [35 ];
M_.mapping.log_c.eqidx = [36 ];
M_.mapping.log_c1.eqidx = [37 ];
M_.mapping.log_c2.eqidx = [38 ];
M_.mapping.log_r.eqidx = [39 ];
M_.mapping.log_r_d.eqidx = [40 ];
M_.mapping.log_pi_h.eqidx = [41 ];
M_.mapping.log_p_h.eqidx = [42 ];
M_.mapping.log_s.eqidx = [43 ];
M_.mapping.log_tot.eqidx = [44 ];
M_.mapping.log_pi.eqidx = [45 ];
M_.mapping.log_w.eqidx = [46 ];
M_.mapping.log_d1.eqidx = [47 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 3 4 7 8 15 16 29 30 32 ];
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(47, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(50, 1);
M_.endo_trends = struct('deflator', cell(47, 1), 'log_deflator', cell(47, 1), 'growth_factor', cell(47, 1), 'log_growth_factor', cell(47, 1));
M_.NNZDerivatives = [173; 286; -1; ];
M_.static_tmp_nbr = [14; 3; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(32) = 1.4105890128;
Y_BAR = M_.params(32);
M_.params(1) = 0.05;
LAMBDA = M_.params(1);
M_.params(2) = 0.997;
BETA = M_.params(2);
M_.params(3) = 2;
SIGMA = M_.params(3);
M_.params(4) = 3.4;
CHI = M_.params(4);
M_.params(5) = 1;
PHI = M_.params(5);
M_.params(9) = 2;
A = M_.params(9);
M_.params(10) = 0.005;
B = M_.params(10);
M_.params(11) = 0.33;
ALPHA = M_.params(11);
M_.params(12) = 0.025;
DELTA = M_.params(12);
M_.params(13) = 2;
KAPPA_P = M_.params(13);
M_.params(14) = 4;
EPSILON = M_.params(14);
M_.params(15) = 5.46;
KAPPA_I = M_.params(15);
M_.params(16) = 3;
EPSILON_B = M_.params(16);
M_.params(19) = 1;
PHI_B = M_.params(19);
M_.params(20) = 1;
PHI_M = M_.params(20);
M_.params(21) = 1;
PHI_G = M_.params(21);
M_.params(22) = 2;
B_BAR = M_.params(22);
M_.params(23) = 0;
M_BAR = M_.params(23);
M_.params(24) = 0;
T1_BAR = M_.params(24);
M_.params(25) = 0;
T2_BAR = M_.params(25);
M_.params(26) = 0.5;
RHO_R = M_.params(26);
M_.params(27) = 10;
PHI_PI = M_.params(27);
M_.params(28) = 10;
PHI_Y = M_.params(28);
M_.params(30) = 1.023069207622869;
R_BAR = M_.params(30);
M_.params(31) = 1.02;
PI_BAR = M_.params(31);
M_.params(34) = 0.2;
DELTA_M = M_.params(34);
M_.params(35) = 0.96;
RHO_A = M_.params(35);
M_.params(36) = 0.95;
RHO_Z = M_.params(36);
M_.params(37) = 0.95;
RHO_G = M_.params(37);
M_.params(40) = 1;
A_BAR = M_.params(40);
M_.params(41) = 1;
Z_BAR = M_.params(41);
M_.params(42) = 0;
G_BAR = M_.params(42);
M_.params(45) = 0.015;
STDERR_A = M_.params(45);
M_.params(46) = 0.01;
STDERR_Z = M_.params(46);
M_.params(47) = 0.01;
STDERR_G = M_.params(47);
M_.params(50) = 0.25;
STDERR_M = M_.params(50);
M_.params(6) = 2;
ETA = M_.params(6);
M_.params(7) = 0.9;
GAMMA = M_.params(7);
M_.params(8) = 0.1;
GAMMA_STAR = M_.params(8);
M_.params(17) = 5;
KAPPA_B = M_.params(17);
M_.params(18) = 0.5;
BF_BAR = M_.params(18);
M_.params(33) = 1.02;
E_BAR = M_.params(33);
M_.params(29) = 2;
PHI_E = M_.params(29);
M_.params(43) = 1;
Y_STAR_BAR = M_.params(43);
M_.params(44) = 1/M_.params(2);
R_STAR_BAR = M_.params(44);
M_.params(38) = 0.95;
RHO_Y_STAR = M_.params(38);
M_.params(39) = 0.99;
RHO_R_STAR = M_.params(39);
M_.params(48) = 0.01;
STDERR_Y_STAR = M_.params(48);
M_.params(49) = 0.01;
STDERR_R_STAR = M_.params(49);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = 1;
oo_.steady_state(2) = 0;
oo_.steady_state(3) = 1;
oo_.steady_state(4) = 1.00301;
oo_.steady_state(5) = 0.989101;
oo_.steady_state(6) = 0.438397;
oo_.steady_state(7) = 11.2001;
oo_.steady_state(8) = 0.280001;
oo_.steady_state(9) = 1.2773;
oo_.steady_state(10) = (-446.999);
oo_.steady_state(11) = 1.00731;
oo_.steady_state(12) = 0.996367;
oo_.steady_state(13) = 0.430421;
oo_.steady_state(14) = 11.7895;
oo_.steady_state(15) = 2.10526;
oo_.steady_state(16) = 0.526316;
oo_.steady_state(17) = (-439.531);
oo_.steady_state(18) = 1.38063;
oo_.steady_state(19) = 0.851062;
oo_.steady_state(20) = 0.589943;
oo_.steady_state(21) = (-588.886);
oo_.steady_state(22) = 1.02307;
oo_.steady_state(23) = 0.028009;
oo_.steady_state(24) = 1.45282;
oo_.steady_state(25) = 1;
oo_.steady_state(26) = 0.744235;
oo_.steady_state(27) = 1.02;
oo_.steady_state(28) = 1.02;
oo_.steady_state(29) = 0.992313;
oo_.steady_state(30) = 1.07494;
oo_.steady_state(31) = 1.02;
oo_.steady_state(32) = 1.02307;
oo_.steady_state(33) = 0.00601805;
oo_.steady_state(34) = 0.00601805;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
options_.solve_algo = 4;
options_.steady.maxit = 5000;
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (M_.params(45))^2;
M_.Sigma_e(2, 2) = (M_.params(47))^2;
M_.Sigma_e(3, 3) = (M_.params(48))^2;
M_.Sigma_e(4, 4) = (M_.params(49))^2;
M_.Sigma_e(5, 5) = (M_.params(50))^2;
options_.hp_filter = 1600;
options_.irf = 101;
options_.nograph = true;
options_.order = 2;
var_list_ = {'v1';'v2';'v'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
options_.hp_filter = 1600;
options_.irf = 101;
options_.nograph = true;
options_.order = 1;
var_list_ = {'log_y';'log_c';'log_c1';'log_c2';'log_r';'log_r_d';'log_pi_h';'log_p_h';'log_s';'log_tot';'log_pi';'log_w';'log_d1'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'Benchmark_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
